[package]
name = "simple_crud_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", features = ["mysql"] }
dotenv = "0.15"
uuid = "1.3.0"
gtk = "0.9.2"
